name: EZ3FS CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build/cmake -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build/cmake
      - name: Test
        run: ctest --test-dir build/cmake --output-on-failure
